# Generated by Django 4.2 on 2023-04-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'User can read all books'), ('super_status', 'Can do whatever')]},
        ),
    ]
